export const SEMANTIC_OPERATIONS: readonly string[];
export function sanitizeSnapshot(input: Record<string,unknown>): Record<string,unknown>;
export function inspectState(doc?:Document,loc?:Location):{state:string};
export function inspectCandidateScope(options?:{doc?:Document}):{scope:'all_talent'|'my_candidates'|'unknown';label:string};
export function ensureAllTalentScope(options?:{doc?:Document}):{scope:'all_talent'|'switching';label:string;changed:boolean};
export function inspectForbiddenFilters(options?:{doc?:Document;loc?:{href?:string}}):{safe:boolean;filters:string[]};
export function inspectAppliedFilters(filters:Record<string,string[]>,options?:{doc?:Document;loc?:{href?:string}}):{safe:boolean;missing:string[];emptyClauses:string[];total:number|null};
export function inspectListState(options?:{doc?:Document;loc?:{href?:string}}):{loading:boolean;page:number;count:number;total:number|null;empty:boolean;resultReady:boolean;queryReady:boolean;signature:string};
export function resetFilters(options?:{doc?:Document}):Promise<{cleared:string[]}>;
export function applyFilters(filters:Record<string,string[]>,options?:{submit?:boolean;reset?:boolean;doc?:Document;loc?:{href?:string}}):Promise<unknown>;
export function applyFilterValue(field:'keywords'|'companies'|'roles'|'cities'|'industries'|'functions',value:string,options?:{doc?:Document}):Promise<{accepted:true;field:string;value:string;committed:true}>;
export function submitSearch(options?:{doc?:Document;loc?:{href?:string}}):{submitted:true;autoSubmitted:boolean};
export function readList(options?:{doc?:Document;page?:number;baseUrl?:string}):Array<Record<string,unknown>>;
export function readDetail(seed:Record<string,unknown>,options?:{doc?:Document;sourceRound?:string;page?:number}):Record<string,unknown>;
export function nextPage(options?:{doc?:Document}):boolean;
