export const SEMANTIC_OPERATIONS=Object.freeze(['inspectState','inspectListState','applyFilters','readList','openDetail','readDetail','nextPage']);
const allowed=Object.freeze(['guluId','name','detailUrl','company','role','city','industry','function','salary','experiences','education','tags','sourceRound','page','capturedAt']);
export function sanitizeSnapshot(input){const output={};for(const key of allowed)if(input[key]!==undefined)output[key]=input[key];output.experiences=Array.isArray(output.experiences)?output.experiences:[];output.education=Array.isArray(output.education)?output.education:[];output.tags=Array.isArray(output.tags)?output.tags:[];for(const key of ['company','role','city','industry','function','salary'])output[key]=String(output[key]??'').slice(0,500);return output;}
const clean=(value)=>String(value??'').replace(/\s+/g,' ').trim();
const visible=(element)=>Boolean(element&&element.getClientRects().length&&getComputedStyle(element).display!=='none'&&getComputedStyle(element).visibility!=='hidden');
const tick=(ms)=>new Promise((resolve)=>setTimeout(resolve,ms));
function filterRoot(doc,names){return [...doc.querySelectorAll('a.search-label')].find((node)=>names.includes(clean(node.textContent)))?.closest('li')??null;}
function setControl(control,value){const setter=Object.getOwnPropertyDescriptor(Object.getPrototypeOf(control),'value')?.set;if(setter)setter.call(control,value);else control.value=value;control.dispatchEvent(new Event('input',{bubbles:true}));control.dispatchEvent(new Event('change',{bubbles:true}));}
function findButton(doc,names){return [...doc.querySelectorAll('button,a')].find((node)=>visible(node)&&names.includes(clean(node.textContent)));}
export function inspectState(doc=globalThis.document,loc=globalThis.location){const body=clean(doc.body?.innerText??doc.body?.textContent),href=String(loc?.href??'');if(/验证码|安全验证|滑块/.test(body))return{state:'captcha'};if(/登录|用户名|密码/.test(body)&&doc.querySelector('input[type=password]'))return{state:'login_required'};if(href.includes('candidate/list'))return{state:'list'};if(href.includes('candidate/detail'))return{state:'detail'};return{state:'unsupported_page'};}
export async function applyFilters(filters,{submit=false,doc=globalThis.document}={}){
 const mapping=[[['关键字','关键词'],filters.keywords],[['公司','公司名称'],filters.companies],[['职位','职位名称'],filters.roles],[['所在城市','城市','工作地点'],filters.cities],[['行业'],filters.industries],[['职能'],filters.functions]];const applied=[],missing=[];
 for(const [labels,values] of mapping){if(!Array.isArray(values)||!values.length)continue;const root=filterRoot(doc,labels);if(!root){missing.push(labels[0]);continue;}root.querySelector('a.search-label')?.click();await tick(80);const controls=[...root.querySelectorAll('input:not([type=hidden]):not([type=radio]),textarea')].filter(visible);const control=controls.find((node)=>node.classList.contains('ui-widget-content'))??controls[0];if(!control){missing.push(labels[0]);continue;}for(const value of values){setControl(control,value);control.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',keyCode:13,which:13,bubbles:true}));await tick(120);}const add=[...root.querySelectorAll('button')].find((node)=>clean(node.textContent)==='添加'&&visible(node));if(add)add.click();applied.push(labels[0]);await tick(80);}
 if(missing.length)throw new Error(`filter_control_changed:${missing.join(',')}`);if(submit){const button=doc.querySelector('.fn-search-filter-bottom button');if(!button||!visible(button))throw new Error('search_control_changed');button.click();}return{applied,missing,submitted:submit};
}
export function readList({doc=globalThis.document,page=1,baseUrl=globalThis.location?.href??'http://121.43.105.7/crm'}={}){const result=[],seen=new Set();for(const link of doc.querySelectorAll('a[href*="candidate/detail"]')){const detailUrl=new URL(link.getAttribute('href'),baseUrl).href;if(seen.has(detailUrl))continue;seen.add(detailUrl);const id=decodeURIComponent(new URL(detailUrl).hash.match(/[?&]id=([^&]+)/)?.[1]??''),row=link.closest('tr,[role=row]')??link.parentElement,links=[...(row?.querySelectorAll('a[href*="candidate/detail"]')??[])];const name=links.map((item)=>clean(item.textContent)).filter((text)=>text&&text!==id&&!/^\d+$/.test(text)).sort((a,b)=>b.length-a.length)[0]??clean(link.textContent),cells=[...(row?.querySelectorAll('td,[role=gridcell]')??[])].map((cell)=>clean(cell.textContent));result.push({guluId:id,name,detailUrl,company:'',role:cells[4]??'',city:'',industry:cells[3]??'',function:cells[4]??'',salary:cells[6]??'',experiences:[],education:[],tags:[],page});}return result;}
export function inspectListState({doc=globalThis.document}={}){const links=[...doc.querySelectorAll('a[href*="candidate/detail"]')].map((node)=>node.getAttribute('href')??'');const active=doc.querySelector('.paging .active,.pagination .active,[aria-current="page"]');const page=Number(clean(active?.textContent))||1;const loading=Boolean(doc.querySelector('.loading,.ant-spin-spinning,.el-loading-mask,.layui-layer-loading,[aria-busy="true"]'));return{loading,page,count:links.length,signature:`${links.length}:${links[0]??''}:${links.at(-1)??''}`};}
const textOf=(doc,selector)=>clean(doc.querySelector(selector)?.textContent);
function sectionAfter(doc,label){const heading=[...doc.querySelectorAll('.fn-heading')].find((node)=>clean(node.textContent).includes(label));return heading?.parentElement?.nextElementSibling??null;}
export function readDetail(seed,{doc=globalThis.document,sourceRound='role',page=1}={}){const work=sectionAfter(doc,'工作经历'),education=sectionAfter(doc,'教育经历'),experience=work?{company:clean(work.querySelector('.company-name')?.textContent),role:clean(work.querySelector('.detail-view-title')?.textContent),period:clean(work.querySelector('.detail-view-time')?.textContent),summary:clean(work.textContent).slice(0,3000)}:null,experiences=experience?[experience]:[];return sanitizeSnapshot({...seed,company:experience?.company||seed.company||'',role:textOf(doc,'.vcard-span .detail-view-title')||experience?.role||seed.role||'',city:textOf(doc,'.detail-view-citys')||seed.city||'',industry:textOf(doc,'.detail-view-industrys')||seed.industry||'',function:textOf(doc,'.detail-view-functions')||seed.function||'',salary:textOf(doc,'.detail-view-annualSalary')||seed.salary||'',experiences,education:education?[clean(education.textContent).slice(0,2000)]:[],tags:[],sourceRound,page,capturedAt:new Date().toISOString()});}
export function nextPage({doc=globalThis.document}={}){const button=doc.querySelector('.paging .fa-chevron-right')?.closest('a')??findButton(doc,['下一页','>','›']);if(!button||button.parentElement?.classList.contains('disabled')||button.getAttribute('aria-disabled')==='true'||button.disabled)return false;button.click();return true;}
export const guluAdapter=Object.freeze({inspectState,inspectListState,applyFilters,readList,readDetail,nextPage});
