const SEMANTIC_OPERATIONS=Object.freeze(['inspectState','inspectCandidateScope','ensureAllTalentScope','inspectForbiddenFilters','inspectAppliedFilters','inspectListState','resetFilters','applyFilters','applyFilterValue','submitSearch','readList','openDetail','readDetail','nextPage']);
const allowed=Object.freeze(['guluId','name','detailUrl','company','role','city','industry','function','salary','experiences','education','tags','sourceRound','sourceStepId','page','capturedAt']);
function sanitizeSnapshot(input){const output={};for(const key of allowed)if(input[key]!==undefined)output[key]=input[key];output.experiences=Array.isArray(output.experiences)?output.experiences:[];output.education=Array.isArray(output.education)?output.education:[];output.tags=Array.isArray(output.tags)?output.tags:[];for(const key of ['company','role','city','industry','function','salary'])output[key]=String(output[key]??'').slice(0,500);return output;}
const clean=(value)=>String(value??'').replace(/\s+/g,' ').trim();
const redactSensitive=(value)=>clean(value).replace(/(?:\+?86[\s-]?)?1[3-9](?:[\s-]?\d){9}\b/g,'[已脱敏]').replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi,'[已脱敏]').replace(/(?:微信|wechat|webchat|wx)[：:\s_-]*[a-zA-Z0-9_-]+/gi,'[已脱敏]').replace(/(?:住址|地址)[：:]?[^,，。;；\n]+/g,'[已脱敏]');
const confirmedAllTalent=new WeakMap();
const hasExplicitEmpty=(doc)=>/暂无(?:数据|记录|人才|候选人?|搜索结果)?|无数据|没有(?:找到)?(?:符合[^。；]{0,30})?(?:数据|人才|候选人?|搜索结果)|未找到(?:符合[^。；]{0,30})?(?:人才|候选人?|结果)|搜索结果为空|共\s*0\s*条|0\s*(?:位|个)\s*(?:人才|候选人?)/.test(clean(doc.body?.innerText??doc.body?.textContent));
const visible=(element)=>Boolean(element&&element.getClientRects().length&&getComputedStyle(element).display!=='none'&&getComputedStyle(element).visibility!=='hidden');
const tick=(ms)=>new Promise((resolve)=>setTimeout(resolve,ms));
const semanticFilterLabels=[['关键字','关键词'],['公司','公司名称'],['职位','职位名称'],['所在城市','城市','工作地点'],['行业'],['职能']];
function filterRoot(doc,names){return [...doc.querySelectorAll('a.search-label')].find((node)=>names.includes(clean(node.textContent)))?.closest('li')??null;}
function decodedUrl(value){let result=String(value??'');for(let i=0;i<3;i+=1){try{const decoded=decodeURIComponent(result);if(decoded===result)break;result=decoded;}catch{break;}}return result;}
function selectedFilterValues(root){if(!root)return[];const values=[];for(const control of root.querySelectorAll('input:not([type=hidden]),textarea')){if(control.type==='radio'||(control.type==='checkbox'&&!control.checked))continue;const value=clean(control.value);if(value&&!['\u4e0d\u9650','\u5168\u90e8'].includes(value))values.push(value);}for(const close of root.querySelectorAll('.ui-icon-close,.tag-close,.select2-selection__choice__remove,.search-choice-close')){const value=clean(close.parentElement?.textContent);if(value)values.push(value);}return[...new Set(values)];}
function inspectForbiddenFilters({doc=globalThis.document,loc=globalThis.location}={}){const decoded=decodedUrl(loc?.href),filters=[];if(/owner__/i.test(decoded))filters.push('owner');if(/type__(?:eq|in)\s*=\s*contact/i.test(decoded))filters.push('type_contact');const ownerValues=selectedFilterValues(filterRoot(doc,['\u62e5\u6709\u8005','Owner']));if(ownerValues.length&&!filters.includes('owner'))filters.push('owner');const typeValues=selectedFilterValues(filterRoot(doc,['\u7c7b\u578b','\u4eba\u624d\u7c7b\u578b','Type']));if(typeValues.some((value)=>/\u8054\u7cfb\u4eba|contact/i.test(value))&&!filters.includes('type_contact'))filters.push('type_contact');return{safe:filters.length===0,filters};}
function resultTotal(doc){const scoped=clean([...doc.querySelectorAll('.paging,.pagination')].map((node)=>node.textContent).join(' '));const body=clean(doc.body?.innerText??doc.body?.textContent);const match=scoped.match(/\(([\d,]+)\)/)||scoped.match(/\u5171\s*([\d,]+)\s*(?:\u6761|\u4f4d|\u4eba)/)||body.match(/\u5171\s*([\d,]+)\s*(?:\u6761|\u4f4d)\s*(?:\u4eba\u624d|\u5019\u9009\u4eba)/);return match?Number(match[1].replace(/,/g,'')):(hasExplicitEmpty(doc)?0:null);}
function gqlClauses(loc){const decoded=decodedUrl(loc?.href),marker=decoded.indexOf('gql=');if(marker<0)return[];const reserved=new Set(['page','savedSearchId']);return decoded.slice(marker+4).split('&').filter((part)=>part&&!reserved.has(part.split('=')[0])&&part.includes('__'));}
function inspectAppliedFilters(filters,{doc=globalThis.document,loc=globalThis.location}={}){const decoded=decodedUrl(loc?.href),clauses=gqlClauses(loc),emptyClauses=clauses.filter((clause)=>!clause.includes('=')||!clean(clause.split('=').slice(1).join('=')));const specs=[['keywords',/^(?:keyword|keywords|q)__/i,true],['companies',/^company(?:_name)?__/i,true],['roles',/^(?:title|position|job_title|role)(?:_name)?__/i,true],['cities',/^(?:location|city)(?:_id)?__/i,false],['industries',/^industry(?:_id)?__/i,false],['functions',/^function(?:_id)?__/i,false]];const missing=[];if(!/[?&]savedSearchId=94096(?:&|$)/.test(decoded))missing.push('savedSearchId');for(const [field,prefix,matchValues] of specs){const values=Array.isArray(filters?.[field])?filters[field].map(clean).filter(Boolean):[];if(!values.length)continue;const matching=clauses.filter((clause)=>prefix.test(clause)&&!emptyClauses.includes(clause));if(!matching.length||(matchValues&&!values.every((value)=>matching.some((clause)=>clean(clause).includes(value)))))missing.push(field);}return{safe:missing.length===0&&emptyClauses.length===0,missing,emptyClauses,total:resultTotal(doc)};}
function setControl(control,value){const setter=Object.getOwnPropertyDescriptor(Object.getPrototypeOf(control),'value')?.set;if(setter)setter.call(control,value);else control.value=value;control.dispatchEvent(new Event('input',{bubbles:true}));control.dispatchEvent(new Event('change',{bubbles:true}));}
function findButton(doc,names){return [...doc.querySelectorAll('button,a')].find((node)=>visible(node)&&names.includes(clean(node.textContent)));}
function inspectState(doc=globalThis.document,loc=globalThis.location){const body=clean(doc.body?.innerText??doc.body?.textContent),href=String(loc?.href??'');if(/验证码|安全验证|滑块/.test(body))return{state:'captcha'};if(/登录|用户名|密码/.test(body)&&doc.querySelector('input[type=password]'))return{state:'login_required'};if(href.includes('candidate/list')){const company=filterRoot(doc,['公司','公司名称']),role=filterRoot(doc,['职位','职位名称']);return{state:company&&role&&doc.querySelector('.fn-search-filter-bottom')?'list':'loading'};}if(href.includes('candidate/detail'))return{state:doc.querySelector('[data-field-name="candidateexperience_set"]')?'detail':'loading'};return{state:'unsupported_page'};}
function scopeTabs(doc){return [...doc.querySelectorAll('a,button,[role="tab"],[role="menuitem"],li,span,label')].filter((node)=>['所有人才','全部人才','所有候选人','我的候选人','我的人才'].includes(clean(node.textContent)));}
function selected(node){let current=node;for(let depth=0;current&&depth<6;depth+=1,current=current.parentElement)if(current.getAttribute?.('aria-selected')==='true'||/(^|\s)(active|selected|current|checked)(\s|$)/i.test(String(current.className??'')))return true;return false;}
function inspectCandidateScope({doc=globalThis.document}={}){const tabs=scopeTabs(doc),active=tabs.find(selected);const label=clean(active?.textContent);if(['所有人才','全部人才','所有候选人'].includes(label))return{scope:'all_talent',label};if(Date.now()-Number(confirmedAllTalent.get(doc)??0)<10_000)return{scope:'all_talent',label:'所有人才'};if(['我的候选人','我的人才'].includes(label))return{scope:'my_candidates',label};return{scope:'unknown',label:''};}
function ensureAllTalentScope({doc=globalThis.document}={}){const current=inspectCandidateScope({doc});if(current.scope==='all_talent')return{...current,changed:false};const target=scopeTabs(doc).find((node)=>['所有人才','全部人才','所有候选人'].includes(clean(node.textContent)));if(!target){const hints=[...new Set([...doc.querySelectorAll('a,button,li,span,label')].map((node)=>clean(node.textContent)).filter((text)=>text.length<=16&&/(人才|候选)/.test(text)))].slice(0,8);throw new Error(`candidate_scope_unavailable:${hints.join('|')||'no_scope_labels'}`);}confirmedAllTalent.set(doc,Date.now());setTimeout(()=>target.click(),0);return{scope:'switching',label:clean(target.textContent),changed:true};}
async function resetFilters({doc=globalThis.document}={}){const cleared=[],roots=[];for(const names of semanticFilterLabels){const root=filterRoot(doc,names);if(root&&!roots.includes(root))roots.push(root);}for(const root of roots){const label=root.querySelector('a.search-label');for(const control of [...root.querySelectorAll('input:not([type=hidden]):not([type=radio]),textarea')])setControl(control,'');for(const close of [...root.querySelectorAll('.ui-icon-close,.tag-close,.select2-selection__choice__remove,.search-choice-close')])close.click();cleared.push(clean(label?.textContent));}return{cleared};}
async function applyFilters(filters,{submit=false,reset=true,doc=globalThis.document,loc=globalThis.location}={}){
 if(reset)await resetFilters({doc});
 const mapping=[[semanticFilterLabels[0],filters.keywords],[semanticFilterLabels[1],filters.companies],[semanticFilterLabels[2],filters.roles],[semanticFilterLabels[3],filters.cities],[semanticFilterLabels[4],filters.industries],[semanticFilterLabels[5],filters.functions]];const applied=[],missing=[];
 for(const [labels,values] of mapping){if(!Array.isArray(values)||!values.length)continue;const root=filterRoot(doc,labels);if(!root){missing.push(labels[0]);continue;}root.querySelector('a.search-label')?.click();await tick(80);const controls=[...root.querySelectorAll('input:not([type=hidden]):not([type=radio]),textarea')].filter(visible);const control=controls.find((node)=>node.classList.contains('ui-widget-content'))??controls[0];if(!control){missing.push(labels[0]);continue;}if(!submit){setControl(control,values.join('，'));applied.push(labels[0]);continue;}const add=[...root.querySelectorAll('button')].find((node)=>clean(node.textContent)==='添加'&&visible(node));for(const value of values){setControl(control,value);if(add)add.click();await tick(120);}applied.push(labels[0]);await tick(80);}
 if(missing.length)throw new Error(`filter_control_changed:${missing.join(',')}`);let autoSubmitted=false;if(submit){const button=doc.querySelector('.fn-search-filter-bottom button');if(button&&visible(button))setTimeout(()=>button.click(),0);else if(String(loc?.href??'').includes('gql='))autoSubmitted=true;else throw new Error('search_control_changed');}return{applied,missing,submitted:submit,autoSubmitted};
}
async function applyFilterValue(field,value,{doc=globalThis.document}={}){const index={keywords:0,companies:1,roles:2,cities:3,industries:4,functions:5}[field];if(index===undefined)throw new Error('unsupported_filter_field');const root=filterRoot(doc,semanticFilterLabels[index]);if(!root)throw new Error(`filter_control_changed:${semanticFilterLabels[index][0]}`);const expected=clean(value);root.querySelector('a.search-label')?.click();await tick(80);const kind=root.querySelector('.fn-operator')?.getAttribute('data-type')||(root.querySelector('.comtree')?'comtree':'tags');
 if(kind==='comtree'){
  root.querySelector('.comtree-title')?.click();await tick(80);const search=[...root.querySelectorAll('input.fn-search-input')].find(visible);if(!search)throw new Error(`filter_value_unresolved:${field}:${expected}`);setControl(search,expected);let matches=[];for(let attempt=0;attempt<10&&!matches.length;attempt+=1){await tick(120);matches=[...root.querySelectorAll('.jqtree-title')].filter((node)=>visible(node)&&clean(node.textContent).includes(expected)).sort((a,b)=>{const exactA=clean(a.textContent)===expected?0:1,exactB=clean(b.textContent)===expected?0:1;if(exactA!==exactB)return exactA-exactB;return Number(a.getAttribute('aria-level')||99)-Number(b.getAttribute('aria-level')||99)});}if(!matches.length)throw new Error(`filter_value_not_found:${field}:${expected}`);const choice=matches.find((node)=>node.parentElement?.querySelector('input[type=checkbox]')),checkbox=choice?.parentElement?.querySelector('input[type=checkbox]');if(!choice||!checkbox)throw new Error(`filter_value_unresolved:${field}:${expected}`);choice.click();await tick(40);const choiceSelected=clean(root.querySelector('.comtree-title span')?.textContent),choiceValue=clean(root.querySelector('input[name=value]')?.value);if((!choiceSelected||choiceSelected==='请选择')&&!choiceValue){checkbox.click();await tick(40);}const confirm=[...root.querySelectorAll('button')].find((node)=>clean(node.textContent)==='确认'&&visible(node));if(!confirm)throw new Error(`filter_value_unresolved:${field}:${expected}`);confirm.click();await tick(80);const selected=clean(root.querySelector('.comtree-title span')?.textContent),hiddenValue=clean(root.querySelector('input[name=value]')?.value);if((!selected||selected==='请选择')&&!hiddenValue)throw new Error(`filter_value_unresolved:${field}:${expected}`);
 }else{
  const control=[...root.querySelectorAll('.tagit-new input.ui-widget-content,input.ui-widget-content')].find(visible);if(!control)throw new Error(`filter_value_unresolved:${field}:${expected}`);setControl(control,expected);const enter=new KeyboardEvent('keydown',{key:'Enter',code:'Enter',bubbles:true});for(const key of ['keyCode','which'])try{Object.defineProperty(enter,key,{value:13})}catch{}control.dispatchEvent(enter);await tick(80);let committed=[...root.querySelectorAll('.tagit-choice')].some((node)=>clean(node.textContent).includes(expected))||[...root.querySelectorAll('input[name=value]')].some((node)=>clean(node.value).includes(expected));if(!committed){const hidden=control.closest('.base-input')?.querySelector('input[name=value]')??root.querySelector('input[name=value]');if(hidden){setControl(hidden,expected);await tick(40);committed=clean(hidden.value).includes(expected);}}if(!committed)throw new Error(`filter_value_unresolved:${field}:${expected}`);
 }
 const add=[...root.querySelectorAll('button')].find((node)=>clean(node.textContent)==='添加'&&visible(node));if(!add)throw new Error(`filter_control_changed:${semanticFilterLabels[index][0]}`);add.click();await tick(80);return{accepted:true,field,value:expected,committed:true};}
function submitSearch({doc=globalThis.document,loc=globalThis.location}={}){const button=doc.querySelector('.fn-search-filter-bottom button');if(button&&visible(button)){setTimeout(()=>button.click(),0);return{submitted:true,autoSubmitted:false};}if(String(loc?.href??'').includes('gql='))return{submitted:true,autoSubmitted:true};throw new Error('search_control_changed');}
function readList({doc=globalThis.document,page=1,baseUrl=globalThis.location?.href??'http://121.43.105.7/crm'}={}){if(hasExplicitEmpty(doc))return[];const result=[],seen=new Set();for(const link of doc.querySelectorAll('a[href*="candidate/detail"]')){const detailUrl=new URL(link.getAttribute('href'),baseUrl).href;if(seen.has(detailUrl))continue;seen.add(detailUrl);const id=decodeURIComponent(new URL(detailUrl).hash.match(/[?&]id=([^&]+)/)?.[1]??''),row=link.closest('tr,[role=row]')??link.parentElement,links=[...(row?.querySelectorAll('a[href*="candidate/detail"]')??[])];const name=links.map((item)=>clean(item.textContent)).filter((text)=>text&&text!==id&&!/^\d+$/.test(text)).sort((a,b)=>b.length-a.length)[0]??clean(link.textContent),cells=[...(row?.querySelectorAll('td,[role=gridcell]')??[])].map((cell)=>clean(cell.textContent));result.push({guluId:id,name,detailUrl,company:'',role:cells[4]??'',city:'',industry:cells[3]??'',function:cells[4]??'',salary:cells[6]??'',experiences:[],education:[],tags:[],page});}return result;}
function inspectListState({doc=globalThis.document,loc=globalThis.location}={}){const links=[...doc.querySelectorAll('a[href*="candidate/detail"]')].map((node)=>node.getAttribute('href')??'');const active=doc.querySelector('.paging .active,.pagination .active,[aria-current="page"]');const page=Number(clean(active?.textContent))||1;const loading=Boolean(doc.querySelector('.loading,.ant-spin-spinning,.el-loading-mask,.layui-layer-loading,[aria-busy="true"]'));const total=resultTotal(doc),empty=hasExplicitEmpty(doc)||total===0;return{loading,page,count:empty?0:links.length,total,empty,resultReady:links.length>0||empty,queryReady:String(loc?.href??'').includes('gql='),signature:empty?'empty':`${links.length}:${links[0]??''}:${links.at(-1)??''}`};}
const textOf=(doc,selector)=>clean(doc.querySelector(selector)?.textContent);
function sectionAfter(doc,label){const heading=[...doc.querySelectorAll('.fn-heading')].find((node)=>clean(node.textContent).includes(label));return heading?.parentElement?.nextElementSibling??null;}
function readDetail(seed,{doc=globalThis.document,sourceRound='role',page=1}={}){
 const work=sectionAfter(doc,'工作经历'),education=sectionAfter(doc,'教育经历');
 const entities=work?[...work.querySelectorAll('[data-expid],.entity.fn-one')]:[];
 const experienceNodes=entities.length?entities:(work?[work]:[]);
 const experiences=experienceNodes.map((node)=>({
  company:clean(node.querySelector('.company-name')?.textContent),
  role:clean(node.querySelector('.detail-view-title')?.textContent),
  period:clean(node.querySelector('.fn-item-key')?.getAttribute('data-original-title')||node.querySelector('.detail-view-time')?.textContent),
  summary:redactSensitive(node.querySelector('.detail-view-description')?.textContent||node.textContent).slice(0,3000),
 }));
 const latest=experiences[0];
 return sanitizeSnapshot({...seed,company:latest?.company||seed.company||'',role:textOf(doc,'.vcard-span .detail-view-title')||latest?.role||seed.role||'',city:textOf(doc,'.detail-view-citys')||seed.city||'',industry:textOf(doc,'.detail-view-industrys')||seed.industry||'',function:textOf(doc,'.detail-view-functions')||seed.function||'',salary:textOf(doc,'.detail-view-annualSalary')||seed.salary||'',experiences,education:education?[clean(education.textContent).slice(0,2000)]:[],tags:[],sourceRound,page,capturedAt:new Date().toISOString()});
}
function nextPage({doc=globalThis.document}={}){const button=doc.querySelector('.paging .fa-chevron-right')?.closest('a')??findButton(doc,['下一页','>','›']);if(!button||button.parentElement?.classList.contains('disabled')||button.getAttribute('aria-disabled')==='true'||button.disabled)return false;button.click();return true;}
const guluAdapter=Object.freeze({SEMANTIC_OPERATIONS,sanitizeSnapshot,inspectState,inspectCandidateScope,ensureAllTalentScope,inspectForbiddenFilters,inspectAppliedFilters,inspectListState,resetFilters,applyFilters,applyFilterValue,submitSearch,readList,readDetail,nextPage});
globalThis.__GULU_ADAPTER__=guluAdapter;
