const SEMANTIC_OPERATIONS=Object.freeze(['inspectState','inspectCandidateScope','ensureAllTalentScope','inspectListState','resetFilters','applyFilters','readList','openDetail','readDetail','nextPage']);
const allowed=Object.freeze(['guluId','name','detailUrl','company','role','city','industry','function','salary','experiences','education','tags','sourceRound','sourceStepId','page','capturedAt']);
function sanitizeSnapshot(input){const output={};for(const key of allowed)if(input[key]!==undefined)output[key]=input[key];output.experiences=Array.isArray(output.experiences)?output.experiences:[];output.education=Array.isArray(output.education)?output.education:[];output.tags=Array.isArray(output.tags)?output.tags:[];for(const key of ['company','role','city','industry','function','salary'])output[key]=String(output[key]??'').slice(0,500);return output;}
const clean=(value)=>String(value??'').replace(/\s+/g,' ').trim();
const confirmedAllTalent=new WeakMap();
const hasExplicitEmpty=(doc)=>/\u6682\u65e0(?:\u6570\u636e|\u8bb0\u5f55)?|\u65e0\u6570\u636e|\u6ca1\u6709.*\u6570\u636e/.test(clean(doc.body?.innerText??doc.body?.textContent));
const visible=(element)=>Boolean(element&&element.getClientRects().length&&getComputedStyle(element).display!=='none'&&getComputedStyle(element).visibility!=='hidden');
const tick=(ms)=>new Promise((resolve)=>setTimeout(resolve,ms));
const semanticFilterLabels=[['关键字','关键词'],['公司','公司名称'],['职位','职位名称'],['所在城市','城市','工作地点'],['行业'],['职能']];
function filterRoot(doc,names){return [...doc.querySelectorAll('a.search-label')].find((node)=>names.includes(clean(node.textContent)))?.closest('li')??null;}
function setControl(control,value){const setter=Object.getOwnPropertyDescriptor(Object.getPrototypeOf(control),'value')?.set;if(setter)setter.call(control,value);else control.value=value;control.dispatchEvent(new Event('input',{bubbles:true}));control.dispatchEvent(new Event('change',{bubbles:true}));}
function findButton(doc,names){return [...doc.querySelectorAll('button,a')].find((node)=>visible(node)&&names.includes(clean(node.textContent)));}
function inspectState(doc=globalThis.document,loc=globalThis.location){const body=clean(doc.body?.innerText??doc.body?.textContent),href=String(loc?.href??'');if(/验证码|安全验证|滑块/.test(body))return{state:'captcha'};if(/登录|用户名|密码/.test(body)&&doc.querySelector('input[type=password]'))return{state:'login_required'};if(href.includes('candidate/list')){const company=filterRoot(doc,['公司','公司名称']),role=filterRoot(doc,['职位','职位名称']);return{state:company&&role&&doc.querySelector('.fn-search-filter-bottom')?'list':'loading'};}if(href.includes('candidate/detail'))return{state:doc.querySelector('[data-field-name="candidateexperience_set"]')?'detail':'loading'};return{state:'unsupported_page'};}
function scopeTabs(doc){return [...doc.querySelectorAll('a,button,[role="tab"],[role="menuitem"],li,span,label')].filter((node)=>['所有人才','全部人才','所有候选人','我的候选人','我的人才'].includes(clean(node.textContent)));}
function selected(node){let current=node;for(let depth=0;current&&depth<6;depth+=1,current=current.parentElement)if(current.getAttribute?.('aria-selected')==='true'||/(^|\s)(active|selected|current|checked)(\s|$)/i.test(String(current.className??'')))return true;return false;}
function inspectCandidateScope({doc=globalThis.document}={}){const tabs=scopeTabs(doc),active=tabs.find(selected);const label=clean(active?.textContent);if(['所有人才','全部人才','所有候选人'].includes(label))return{scope:'all_talent',label};if(Date.now()-Number(confirmedAllTalent.get(doc)??0)<10_000)return{scope:'all_talent',label:'所有人才'};if(['我的候选人','我的人才'].includes(label))return{scope:'my_candidates',label};return{scope:'unknown',label:''};}
function ensureAllTalentScope({doc=globalThis.document}={}){const current=inspectCandidateScope({doc});if(current.scope==='all_talent')return{...current,changed:false};const target=scopeTabs(doc).find((node)=>['所有人才','全部人才','所有候选人'].includes(clean(node.textContent)));if(!target){const hints=[...new Set([...doc.querySelectorAll('a,button,li,span,label')].map((node)=>clean(node.textContent)).filter((text)=>text.length<=16&&/(人才|候选)/.test(text)))].slice(0,8);throw new Error(`candidate_scope_unavailable:${hints.join('|')||'no_scope_labels'}`);}confirmedAllTalent.set(doc,Date.now());setTimeout(()=>target.click(),0);return{scope:'switching',label:clean(target.textContent),changed:true};}
async function resetFilters({doc=globalThis.document}={}){const cleared=[],roots=[];for(const names of semanticFilterLabels){const root=filterRoot(doc,names);if(root&&!roots.includes(root))roots.push(root);}for(const root of roots){const label=root.querySelector('a.search-label');label?.click();await tick(30);for(const control of [...root.querySelectorAll('input:not([type=hidden]):not([type=radio]),textarea')])setControl(control,'');for(const close of [...root.querySelectorAll('.ui-icon-close,.tag-close,.select2-selection__choice__remove,.search-choice-close')])if(visible(close))close.click();cleared.push(clean(label?.textContent));}return{cleared};}
async function applyFilters(filters,{submit=false,reset=true,doc=globalThis.document,loc=globalThis.location}={}){
 if(reset)await resetFilters({doc});
 const mapping=[[semanticFilterLabels[0],filters.keywords],[semanticFilterLabels[1],filters.companies],[semanticFilterLabels[2],filters.roles],[semanticFilterLabels[3],filters.cities],[semanticFilterLabels[4],filters.industries],[semanticFilterLabels[5],filters.functions]];const applied=[],missing=[];
 for(const [labels,values] of mapping){if(!Array.isArray(values)||!values.length)continue;const root=filterRoot(doc,labels);if(!root){missing.push(labels[0]);continue;}root.querySelector('a.search-label')?.click();await tick(80);const controls=[...root.querySelectorAll('input:not([type=hidden]):not([type=radio]),textarea')].filter(visible);const control=controls.find((node)=>node.classList.contains('ui-widget-content'))??controls[0];if(!control){missing.push(labels[0]);continue;}if(!submit){setControl(control,values.join('，'));applied.push(labels[0]);continue;}for(const value of values){setControl(control,value);control.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',keyCode:13,which:13,bubbles:true}));await tick(120);}const add=[...root.querySelectorAll('button')].find((node)=>clean(node.textContent)==='添加'&&visible(node));if(add)add.click();applied.push(labels[0]);await tick(80);}
 if(missing.length)throw new Error(`filter_control_changed:${missing.join(',')}`);let autoSubmitted=false;if(submit){const button=doc.querySelector('.fn-search-filter-bottom button');if(button&&visible(button))button.click();else if(String(loc?.href??'').includes('gql='))autoSubmitted=true;else throw new Error('search_control_changed');}return{applied,missing,submitted:submit,autoSubmitted};
}
function readList({doc=globalThis.document,page=1,baseUrl=globalThis.location?.href??'http://121.43.105.7/crm'}={}){if(hasExplicitEmpty(doc))return[];const result=[],seen=new Set();for(const link of doc.querySelectorAll('a[href*="candidate/detail"]')){const detailUrl=new URL(link.getAttribute('href'),baseUrl).href;if(seen.has(detailUrl))continue;seen.add(detailUrl);const id=decodeURIComponent(new URL(detailUrl).hash.match(/[?&]id=([^&]+)/)?.[1]??''),row=link.closest('tr,[role=row]')??link.parentElement,links=[...(row?.querySelectorAll('a[href*="candidate/detail"]')??[])];const name=links.map((item)=>clean(item.textContent)).filter((text)=>text&&text!==id&&!/^\d+$/.test(text)).sort((a,b)=>b.length-a.length)[0]??clean(link.textContent),cells=[...(row?.querySelectorAll('td,[role=gridcell]')??[])].map((cell)=>clean(cell.textContent));result.push({guluId:id,name,detailUrl,company:'',role:cells[4]??'',city:'',industry:cells[3]??'',function:cells[4]??'',salary:cells[6]??'',experiences:[],education:[],tags:[],page});}return result;}
function inspectListState({doc=globalThis.document,loc=globalThis.location}={}){const links=[...doc.querySelectorAll('a[href*="candidate/detail"]')].map((node)=>node.getAttribute('href')??'');const active=doc.querySelector('.paging .active,.pagination .active,[aria-current="page"]');const page=Number(clean(active?.textContent))||1;const loading=Boolean(doc.querySelector('.loading,.ant-spin-spinning,.el-loading-mask,.layui-layer-loading,[aria-busy="true"]'));const empty=hasExplicitEmpty(doc);return{loading,page,count:empty?0:links.length,empty,resultReady:links.length>0||empty,queryReady:String(loc?.href??'').includes('gql='),signature:empty?'empty':`${links.length}:${links[0]??''}:${links.at(-1)??''}`};}
const textOf=(doc,selector)=>clean(doc.querySelector(selector)?.textContent);
function sectionAfter(doc,label){const heading=[...doc.querySelectorAll('.fn-heading')].find((node)=>clean(node.textContent).includes(label));return heading?.parentElement?.nextElementSibling??null;}
function readDetail(seed,{doc=globalThis.document,sourceRound='role',page=1}={}){
 const work=sectionAfter(doc,'工作经历'),education=sectionAfter(doc,'教育经历');
 const entities=work?[...work.querySelectorAll('[data-expid],.entity.fn-one')]:[];
 const experienceNodes=entities.length?entities:(work?[work]:[]);
 const experiences=experienceNodes.map((node)=>({
  company:clean(node.querySelector('.company-name')?.textContent),
  role:clean(node.querySelector('.detail-view-title')?.textContent),
  period:clean(node.querySelector('.fn-item-key')?.getAttribute('data-original-title')||node.querySelector('.detail-view-time')?.textContent),
  summary:clean(node.querySelector('.detail-view-description')?.textContent||node.textContent).slice(0,3000),
 }));
 const latest=experiences[0];
 return sanitizeSnapshot({...seed,company:latest?.company||seed.company||'',role:textOf(doc,'.vcard-span .detail-view-title')||latest?.role||seed.role||'',city:textOf(doc,'.detail-view-citys')||seed.city||'',industry:textOf(doc,'.detail-view-industrys')||seed.industry||'',function:textOf(doc,'.detail-view-functions')||seed.function||'',salary:textOf(doc,'.detail-view-annualSalary')||seed.salary||'',experiences,education:education?[clean(education.textContent).slice(0,2000)]:[],tags:[],sourceRound,page,capturedAt:new Date().toISOString()});
}
function nextPage({doc=globalThis.document}={}){const button=doc.querySelector('.paging .fa-chevron-right')?.closest('a')??findButton(doc,['下一页','>','›']);if(!button||button.parentElement?.classList.contains('disabled')||button.getAttribute('aria-disabled')==='true'||button.disabled)return false;button.click();return true;}
const guluAdapter=Object.freeze({SEMANTIC_OPERATIONS,sanitizeSnapshot,inspectState,inspectCandidateScope,ensureAllTalentScope,inspectListState,resetFilters,applyFilters,readList,readDetail,nextPage});
globalThis.__GULU_ADAPTER__=guluAdapter;
