import {describe,expect,it} from 'vitest';import {readFile} from 'node:fs/promises';
describe('adaptive campaign extension contract',()=>{
  it('preflights arbitrary steps and checks dedupe before opening details',async()=>{const source=await readFile(new URL('../extension/background.js',import.meta.url),'utf8');expect(source).toContain('async function runCampaignTask');expect(source).toContain("'preflight_completed'");expect(source).toContain("'applyFilterValue'");expect(source).toContain("'submitSearch'");expect(source).toContain('/candidates/check');expect(source).toContain('sourceStepId: step.id');expect(source).toContain('candidate:${task.id}:${step.id}:${seed.guluId}');});
  it('probes verified effective filters before reading any campaign candidate',async()=>{const source=await readFile(new URL('../extension/background.js',import.meta.url),'utf8');const start=source.indexOf('async function runCampaignTask');const end=source.indexOf('\nasync function runOnce',start);const campaign=source.slice(start,end);const verify=campaign.indexOf("'inspectAppliedFilters'");const probe=campaign.indexOf("'step_probed'");const read=campaign.indexOf("'readList'");expect(verify).toBeGreaterThan(0);expect(probe).toBeGreaterThan(verify);expect(read).toBeGreaterThan(probe);expect(campaign).toContain("probe.action !== 'read'");expect(campaign).toContain('applied.total < 1 || applied.total > 100');});
  it('reports missing Gulu taxonomy values to the adaptive planner instead of pausing',async()=>{const source=await readFile(new URL('../extension/background.js',import.meta.url),'utf8');expect(source).toContain("filter_value_not_found:");expect(source).toContain("'filter_unavailable'");});
  it('gives both unresolved and apparently missing tree values a main-world retry',async()=>{const source=await readFile(new URL('../extension/background.js',import.meta.url),'utf8');expect(source).toContain('filter_value_(?:unresolved|not_found)');});
  it('never infers an empty campaign result from a temporarily blank table',async()=>{const source=await readFile(new URL('../extension/background.js',import.meta.url),'utf8');expect(source).not.toContain('inferredEmpty');expect(source).not.toContain('zeroCount >= 10');});
  it('never records a non-DeepSeek fallback search-fit result',async()=>{const source=await readFile(new URL('../src/server/app.ts',import.meta.url),'utf8');expect(source).not.toContain("model:'fallback'");});
  it('uses the step status as well as the possibly stale task phase for the five-person calibration cap',async()=>{const source=await readFile(new URL('../extension/background.js',import.meta.url),'utf8');expect(source).toContain("const calibrating = task.phase === 'calibration' || progress.status === 'pending' || progress.status === 'calibrating'");expect(source).toContain('const target = calibrating ? Math.min(5, step.limit) : step.limit');expect(source).toContain('if (calibrating && read >= 5)');});
  it('never changes keyword merely because the first five candidates are low fit',async()=>{const source=await readFile(new URL('../src/server/app.ts',import.meta.url),'utf8');expect(source).not.toContain("if(progress.highFitCount===0)");expect(source).not.toContain("if(progress.uniqueCount<3)");expect(source).toContain("req.body?.exhausted?'next_step':'continue'");});
});
