import {useEffect,useMemo,useState} from 'react';
import {api,type ConnectorStatus,type GuluPlan,type GuluTask,type JobPack,type JobSummary,type ResultItem,type RunRecord} from './api.js';
import './styles.css';
type View='jobs'|'rules'|'run'|'results'|'settings'; const labels={recommend:'推荐',review:'复核',exclude:'排除'} as const;
const split=(value:string)=>value.split(/[,，\n]/).map(x=>x.trim()).filter(Boolean);

export function App(){
 const [view,setView]=useState<View>('jobs'),[jobs,setJobs]=useState<JobSummary[]>([]),[selected,setSelected]=useState(''),[pack,setPack]=useState<JobPack|null>(null),[results,setResults]=useState<ResultItem[]>([]);
 const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[title,setTitle]=useState('制造业销售经理'),[source,setSource]=useState('寻找具备大型制造企业客户拓展经验，能够负责关键客户增长的销售经理。'),[file,setFile]=useState<File|null>(null);
 const [demo,setDemo]=useState<RunRecord|null>(null),[connector,setConnector]=useState<ConnectorStatus|null>(null),[pairing,setPairing]=useState<{code:string;expiresAt:string}|null>(null),[plan,setPlan]=useState<GuluPlan|null>(null),[task,setTask]=useState<GuluTask|null>(null);
 const [filter,setFilter]=useState('all'),[baseUrl,setBaseUrl]=useState('https://api.deepseek.com'),[model,setModel]=useState('deepseek-v4-flash');
 const refreshJobs=()=>api.jobs().then(x=>setJobs(x.items)).catch(e=>setNotice(e.message)); const refreshConnector=()=>api.connectorStatus().then(setConnector).catch(()=>setConnector(null));
 useEffect(()=>{refreshJobs();refreshConnector();const timer=setInterval(refreshConnector,10000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(!task||['completed','stopped','failed'].includes(task.status))return;const timer=setInterval(()=>api.getRun<GuluTask>(task.id).then(setTask).catch(()=>{}),2000);return()=>clearInterval(timer)},[task?.id,task?.status]);
 const openJob=async(id:string,next:View='rules')=>{setBusy(true);try{const data=await api.getJob(id);setSelected(id);setPack(data.pack);setPlan(null);setTask(null);setView(next);if(next==='results')setResults((await api.results(id)).items)}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
 const create=async()=>{setBusy(true);try{const created=file?await api.importFile(title,file):await api.create({title,sourceText:source});setSelected(created.job_id);setPack(created);setView('rules');setNotice('岗位草稿已生成，请审核后批准。');await refreshJobs()}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
 const updateList=(key:string,value:string[])=>setPack((p:any)=>({...p,[key.split('.')[0]]:{...p[key.split('.')[0]],[key.split('.')[1]]:value}}));
 const save=async()=>{if(!pack)return;setBusy(true);try{const next=await api.revise(selected,pack);setPack(next);setNotice(`已保存规则 v${next.rule_version}`)}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
 const approve=async()=>{if(!pack)return;setBusy(true);try{setPack(await api.approve(selected,pack.rule_version));setNotice('规则已批准，可以生成谷露搜索计划。');await refreshJobs()}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
 const generatePlan=async()=>{setBusy(true);try{setPlan(await api.generateGuluPlan(selected));setNotice('DeepSeek 已生成两轮搜索条件，请人工确认。')}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
 const confirmPlan=async()=>{if(!plan)return;setBusy(true);try{setPlan(await api.confirmGuluPlan(selected,plan));setNotice('搜索条件已人工确认。')}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
 const startGulu=async(mode:GuluTask['mode'])=>{setBusy(true);try{setTask(await api.startGulu(selected,mode));setNotice(mode==='dry-run'?'已创建只填写、不提交的 dry-run。':mode==='pilot'?'已创建真实 5 人试跑。':'已创建正式双轮任务。')}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
 const shown=useMemo(()=>filter==='all'?results:results.filter(x=>x.label===filter),[results,filter]);
 const nav=(id:View,text:string)=><button className={view===id?'nav active':'nav'} onClick={()=>setView(id)}>{text}</button>;
 return <div className="app-shell"><aside><div className="brand"><div className="logo">谷</div><div><strong>谷露简历筛选</strong><small>DEEPSEEK · LOCAL</small></div></div><div className="local-pill"><i/>仅在本机运行</div><nav>{nav('jobs','岗位管理')}{nav('rules','规则审核')}{nav('run','运行中心')}{nav('results','候选结果')}{nav('settings','连接与设置')}</nav><div className="safety"><b>安全边界</b><p>只读筛选，不写入谷露</p><p>最终决定由人工审核</p></div></aside>
 <main><header><div><p className="eyebrow">GULU SCREENING v1.1.0</p><h1>{({jobs:'岗位工作台',rules:'规则审核',run:'运行中心',results:'候选结果',settings:'连接与设置'} as const)[view]}</h1></div><span className="shield">本机服务 · DeepSeek AI</span></header>{notice&&<div className="notice" onClick={()=>setNotice('')}>{notice}<span>×</span></div>}{busy&&<div className="progress"><i/></div>}
 {view==='jobs'&&<section className="grid jobs-layout"><div className="panel create-card"><div className="panel-title"><span className="step">01</span><div><h2>创建岗位</h2><p>粘贴需求，或上传 Word / PDF</p></div></div><label>岗位名称<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>客户要求与 JD<textarea rows={8} value={source} onChange={e=>setSource(e.target.value)}/></label><label className="upload">上传 DOCX / PDF / TXT<input type="file" accept=".docx,.pdf,.txt" onChange={e=>setFile(e.target.files?.[0]||null)}/><span>{file?.name||'选择本机文件（最大 15MB）'}</span></label><button className="primary wide" onClick={create}>生成岗位包 →</button></div><div className="panel"><div className="panel-title"><span className="step dark">02</span><div><h2>岗位列表</h2><p>批准规则后才能连接真实谷露</p></div></div><div className="job-list">{jobs.length?jobs.map(j=><button className="job-row" key={j.id} onClick={()=>openJob(j.id)}><div><b>{j.title}</b><small>{new Date(j.created_at+'Z').toLocaleString()}</small></div><span className={`status ${j.status}`}>{j.status==='approved'?'已批准':`草稿 v${j.current_rule_version}`}</span><em>›</em></button>):<Empty text="还没有岗位"/>}</div></div></section>}
 {view==='rules'&&<section>{!pack?<Empty text="请先选择岗位"/>:<><div className="flow-head"><div><span className={`status ${pack.approval.status}`}>{pack.approval.status==='approved'?'已批准':'草稿'}</span><h2>规则版本 v{pack.rule_version}</h2></div><div><a className="button ghost" href={`/api/jobs/${selected}/guide.docx`}>下载岗位说明</a></div></div><div className="rules-grid"><RuleList title="硬条件" value={pack.constraints.hard} onChange={v=>updateList('constraints.hard',v)}/><RuleList title="加分项" value={pack.constraints.soft} onChange={v=>updateList('constraints.soft',v)}/><RuleList title="目标公司" value={pack.companies.target} onChange={v=>updateList('companies.target',v)}/><RuleList title="目标职位" value={pack.roles.exact} onChange={v=>updateList('roles.exact',v)}/><RuleList title="正面证据" value={pack.evidence.required} onChange={v=>updateList('evidence.required',v)}/><RuleList title="明确反证" value={pack.evidence.negative} onChange={v=>updateList('evidence.negative',v)}/></div><div className="action-bar"><button className="ghost" onClick={save}>保存新版本</button><button className="primary" onClick={approve} disabled={pack.approval.status==='approved'}>批准规则</button><button className="accent" onClick={()=>setView('run')} disabled={pack.approval.status!=='approved'}>进入运行中心 →</button></div></>}</section>}
 {view==='run'&&<section>{!selected?<Empty text="请先选择并批准一个岗位"/>:<div className="settings-grid"><div className="panel"><div className="panel-title"><span className="step">真</span><div><h2>真实谷露后台筛选</h2><p>网站可关闭；本机服务、Chrome 与登录需保持在线</p></div></div><Connection status={connector}/>{!plan?<button className="primary wide" onClick={generatePlan} disabled={pack?.approval.status!=='approved'}>用 DeepSeek 生成搜索计划</button>:<PlanEditor plan={plan} onChange={setPlan}/>} {plan&&<div className="action-bar">{plan.status==='draft'?<button className="primary" onClick={confirmPlan}>人工确认搜索条件</button>:<><button className="ghost" onClick={()=>startGulu('dry-run')}>只填写 dry-run</button><button className="accent" onClick={()=>startGulu('pilot')}>真实 5 人试跑</button><button className="primary" onClick={()=>startGulu('formal')}>正式双轮各 50</button></>}</div>}{task&&<TaskProgress task={task} onUpdate={setTask}/>}</div><div className="panel"><div className="panel-title"><span className="step dark">备</span><div><h2>离线模拟回退</h2><p>不操作真实谷露，可随时验证岗位规则</p></div></div>{!demo?<button className="ghost wide" onClick={async()=>setDemo(await api.runDemo(selected))}>创建模拟运行</button>:<><p className="center">{demo.cursor} / {demo.total} · {demo.status}</p><div className="action-bar"><button className="ghost" onClick={async()=>setDemo(await api.processRun(demo.id,5))}>处理下一批</button></div></>}</div></div>}</section>}
 {view==='results'&&<Results selected={selected} items={results} shown={shown} filter={filter} setFilter={setFilter} reload={()=>selected&&api.results(selected).then(x=>setResults(x.items))}/>}
 {view==='settings'&&<section className="settings-grid"><div className="panel"><h2>谷露扩展配对</h2><Connection status={connector}/><p>1. 在 Chrome 扩展页加载本项目的 <b>extension</b> 文件夹。</p><p>2. 生成配对码，在扩展弹窗中输入。</p>{pairing?<div className="metric blue"><small>10 分钟内有效的配对码</small><strong>{pairing.code}</strong></div>:<button className="primary" onClick={async()=>setPairing(await api.createPairing())}>生成一次性配对码</button>}</div><div className="panel"><h2>DeepSeek 连接</h2><label>API 地址<input value={baseUrl} onChange={e=>setBaseUrl(e.target.value)}/></label><label>模型<input value={model} onChange={e=>setModel(e.target.value)}/></label><button className="primary" onClick={async()=>{const r=await api.testDeepSeek(baseUrl,model);setNotice(r.ok?`连接成功 · ${r.model}`:`连接失败：${r.errorType}`)}}>测试连接</button><p className="muted">Key 只从本机 .env 读取，不显示、不写数据库。</p></div></section>}
 </main></div>;
}

function Empty({text}:{text:string}){return <div className="empty large">◇<br/>{text}</div>}
function RuleList({title,value,onChange}:{title:string;value:string[];onChange:(v:string[])=>void}){return <div className="rule-card"><h3>{title}</h3><p>每行一条，可人工修改</p><textarea value={value.join('\n')} onChange={e=>onChange(split(e.target.value))}/></div>}
function Connection({status}:{status:ConnectorStatus|null}){return <div className="run-steps"><div><b>{status?.paired?'✓':'1'}</b><span>扩展{status?.paired?'已配对':'未配对'}</span></div><div><b>{status?.extensionOnline?'✓':'2'}</b><span>Chrome {status?.extensionOnline?'在线':'离线'}</span></div><div><b>{status?.guluStatus==='online'||status?.guluStatus==='paired'?'✓':'3'}</b><span>谷露 {status?.guluStatus||'待检查'}</span></div></div>}
function PlanEditor({plan,onChange}:{plan:GuluPlan;onChange:(p:GuluPlan)=>void}){const update=(index:number,key:keyof GuluPlan['rounds'][number]['filters'],value:string)=>{const rounds=structuredClone(plan.rounds);rounds[index].filters[key]=split(value);onChange({...plan,rounds})};return <div><h3>搜索条件预览 · {plan.status==='confirmed'?'已确认':'待确认'}</h3>{plan.rounds.map((round,index)=><div className="rule-card" key={round.kind}><h3>{round.kind==='company'?'公司轮':'职位轮'} · 最多 {round.limit} 人</h3>{(['keywords','companies','roles','cities','industries','functions'] as const).map(key=><label key={key}>{({keywords:'关键词',companies:'公司',roles:'职位',cities:'城市',industries:'行业',functions:'职能'} as const)[key]}<input disabled={plan.status==='confirmed'} value={round.filters[key].join('，')} onChange={e=>update(index,key,e.target.value)}/></label>)}</div>)}</div>}
function TaskProgress({task,onUpdate}:{task:GuluTask;onUpdate:(t:GuluTask)=>void}){return <div className="rule-card"><h3>{task.mode} · {task.status}</h3><p>{task.currentRound==='company'?'公司轮':'职位轮'} · 第 {task.page} 页 · 已读取 {task.readCount} · 去重 {task.dedupedCount} · 已分析 {task.analyzedCount} · Token {task.inputTokens+task.outputTokens}</p>{task.lastError&&<p className="notice">需要处理：{task.lastError}</p>}<div className="action-bar">{task.status==='running'||task.status==='queued'?<button className="ghost" onClick={async()=>onUpdate(await api.pauseRun<GuluTask>(task.id))}>暂停</button>:task.status==='paused'||task.status==='needs_attention'?<button className="ghost" onClick={async()=>onUpdate(await api.resumeRun<GuluTask>(task.id))}>恢复</button>:null}<button className="primary" onClick={async()=>onUpdate(await api.stopRun(task.id))}>紧急停止</button></div></div>}
function Results({selected,items,shown,filter,setFilter,reload}:{selected:string;items:ResultItem[];shown:ResultItem[];filter:string;setFilter:(v:string)=>void;reload:()=>void}){if(!selected)return <Empty text="请先完成一次筛选"/>;const counts={recommend:items.filter(x=>x.label==='recommend').length,review:items.filter(x=>x.label==='review').length,exclude:items.filter(x=>x.label==='exclude').length};return <section><div className="metrics"><Metric label="全部" value={items.length}/><Metric label="推荐" value={counts.recommend}/><Metric label="复核" value={counts.review}/><Metric label="排除" value={counts.exclude}/></div><div className="results-toolbar"><div className="filters">{[['all','全部'],['recommend','推荐'],['review','复核'],['exclude','排除']].map(x=><button key={x[0]} className={filter===x[0]?'on':''} onClick={()=>setFilter(x[0])}>{x[1]}</button>)}</div><div><button className="ghost" onClick={reload}>刷新</button><a className="button primary" href={`/api/jobs/${selected}/export.xlsx`}>导出 Excel</a></div></div><div className="result-list">{shown.map(item=><ResultCard key={item.candidateId} item={item} jobId={selected} reload={reload}/>)}</div></section>}
function Metric({label,value}:{label:string;value:number}){return <div className="metric blue"><small>{label}</small><strong>{value}</strong></div>}
function ResultCard({item,jobId,reload}:{item:ResultItem;jobId:string;reload:()=>void}){const [note,setNote]=useState(item.note),[status,setStatus]=useState(item.reviewStatus);return <article className="result-card"><div className={`label ${item.label}`}>{labels[item.label]}</div><div className="person"><h3>{item.name}</h3><p>{item.currentCompany} · {item.currentRole}</p></div><div className="evidence"><b>{item.reasonCode}</b>{item.evidence.map(x=><p key={x}>• {x}</p>)}</div><div className="review"><select value={status} onChange={e=>setStatus(e.target.value)}><option>未审核</option><option>已复核</option><option>需沟通</option></select><input value={note} onChange={e=>setNote(e.target.value)} placeholder="人工备注"/><button onClick={async()=>{await api.review(jobId,item.candidateId,item.ruleVersion,status,note);reload()}}>保存</button></div></article>}
