import { useEffect, useMemo, useState } from 'react';
import { api, type JobPack, type JobSummary, type ResultItem, type RunRecord } from './api.js';
import './styles.css';

const labels={recommend:'推荐',review:'复核',exclude:'排除'} as const;
type View='jobs'|'rules'|'run'|'results'|'settings';

export function App(){
  const [view,setView]=useState<View>('jobs');const [jobs,setJobs]=useState<JobSummary[]>([]);const [selected,setSelected]=useState('');
  const [pack,setPack]=useState<JobPack|null>(null);const [results,setResults]=useState<ResultItem[]>([]);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');
  const [currentRun,setCurrentRun]=useState<RunRecord|null>(null);
  const [title,setTitle]=useState('制造业销售经理');const [source,setSource]=useState('寻找具备大型制造企业客户拓展经历、能够负责关键客户增长的销售经理。');const [file,setFile]=useState<File|null>(null);
  const [filter,setFilter]=useState('all');const [baseUrl,setBaseUrl]=useState('https://api.deepseek.com');const [model,setModel]=useState('deepseek-v4-flash');
  const refreshJobs=()=>api.jobs().then(x=>setJobs(x.items)).catch(e=>setNotice(e.message));
  useEffect(()=>{refreshJobs()},[]);
  const openJob=async(id:string,next:View='rules')=>{setBusy(true);try{const data=await api.getJob(id);setSelected(id);setPack(data.pack);setView(next);if(next==='results'){setResults((await api.results(id)).items)}}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
  const create=async()=>{setBusy(true);try{const created=file?await api.importFile(title,file):await api.create({title,sourceText:source});setSelected(created.job_id);setPack(created);setView('rules');setNotice('岗位草稿已创建，请审核规则后批准。');await refreshJobs()}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
  const saveRules=async()=>{if(!pack)return;setBusy(true);try{const next=await api.revise(selected,pack);setPack(next);setNotice(`已保存为规则 v${next.rule_version} 草稿`) }catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
  const approve=async()=>{if(!pack)return;setBusy(true);try{const next=await api.approve(selected,pack.rule_version);setPack(next);setNotice('规则已批准，可以开始筛选。');await refreshJobs()}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
  const startRun=async()=>{setBusy(true);try{setCurrentRun(await api.runDemo(selected));setNotice('运行已创建，可以分批处理并随时暂停。')}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
  const processRun=async()=>{if(!currentRun)return;setBusy(true);try{const next=await api.processRun(currentRun.id,5);setCurrentRun(next);if(next.status==='completed'){setResults((await api.results(selected)).items);setNotice('模拟双轮筛选完成，结果已去重。')}}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
  const updateList=(key:string,value:string[])=>setPack((p:any)=>({...p,[key.split('.')[0]]:{...p[key.split('.')[0]],[key.split('.')[1]]:value}}));
  const shown=useMemo(()=>filter==='all'?results:results.filter(r=>r.label===filter),[results,filter]);
  const counts=useMemo(()=>({recommend:results.filter(x=>x.label==='recommend').length,review:results.filter(x=>x.label==='review').length,exclude:results.filter(x=>x.label==='exclude').length}),[results]);
  const nav=(id:View,text:string,icon:string)=><button className={view===id?'nav active':'nav'} onClick={()=>setView(id)}><span>{icon}</span>{text}</button>;
  return <div className="app-shell">
    <aside><div className="brand"><div className="logo">谷</div><div><strong>谷露简历筛选</strong><small>Recruiting Intelligence</small></div></div>
      <div className="local-pill"><i/>仅在本机运行</div><nav>{nav('jobs','岗位管理','▦')}{nav('rules','规则审核','✓')}{nav('run','运行中心','▶')}{nav('results','候选结果','◎')}{nav('settings','设置与诊断','⚙')}</nav>
      <div className="safety"><b>安全边界</b><p>只读辅助筛选</p><p>最终决定由人工审核</p></div>
    </aside>
    <main><header><div><p className="eyebrow">GULU SCREENING MVP</p><h1>{view==='jobs'?'岗位工作台':view==='rules'?'规则审核':view==='run'?'运行中心':view==='results'?'候选结果':'设置与诊断'}</h1></div><div className="header-actions"><span className="shield">◆ 数据保存在本机</span><button className="primary" onClick={()=>setView('jobs')}>＋ 创建岗位</button></div></header>
      {notice&&<div className="notice" onClick={()=>setNotice('')}>{notice}<span>×</span></div>}
      {busy&&<div className="progress"><i/></div>}
      {view==='jobs'&&<section className="grid jobs-layout"><div className="panel create-card"><div className="panel-title"><span className="step">01</span><div><h2>创建岗位</h2><p>粘贴需求，或上传 Word / PDF</p></div></div><label>岗位名称<input value={title} onChange={e=>setTitle(e.target.value)} /></label><label>客户要求与 JD<textarea rows={8} value={source} onChange={e=>setSource(e.target.value)} /></label><label className="upload">上传 DOCX / PDF<input type="file" accept=".docx,.pdf,.txt" onChange={e=>setFile(e.target.files?.[0]||null)}/><span>{file?file.name:'选择本机文件（最大 15MB）'}</span></label><button className="primary wide" disabled={busy} onClick={create}>生成岗位包 →</button></div>
        <div className="panel"><div className="panel-title"><span className="step dark">02</span><div><h2>最近岗位</h2><p>规则批准后才能启动筛选</p></div></div><div className="job-list">{jobs.length===0?<div className="empty">还没有岗位<br/><small>从左侧创建第一个岗位</small></div>:jobs.map(j=><button className="job-row" key={j.id} onClick={()=>openJob(j.id)}><div><b>{j.title}</b><small>{new Date(j.created_at+'Z').toLocaleString()}</small></div><span className={`status ${j.status}`}>{j.status==='approved'?'已批准':'草稿 v'+j.current_rule_version}</span><em>›</em></button>)}</div></div></section>}
      {view==='rules'&&<section>{!pack?<Empty text="请先从岗位管理中选择一个岗位"/>:<><div className="flow-head"><div><span className={`status ${pack.approval.status}`}>{pack.approval.status==='approved'?'已批准':'草稿'}</span><h2>规则版本 v{pack.rule_version}</h2></div><div><button className="button ghost" onClick={async()=>{if(window.confirm('确认删除这个岗位及其本机数据？此操作不可撤销。')){await api.deleteJob(selected);setSelected('');setPack(null);setView('jobs');await refreshJobs()}}}>删除岗位</button><a className="button ghost" href={`/api/jobs/${selected}/guide.docx`}>下载岗位说明</a><a className="button ghost" href={`/api/jobs/${selected}/job-pack.json`}>下载 JSON</a></div></div><div className="rules-grid"><RuleList title="硬条件" help="缺少信息不会直接排除" value={pack.constraints.hard} onChange={v=>updateList('constraints.hard',v)}/><RuleList title="加分项" help="用于识别更高匹配度" value={pack.constraints.soft} onChange={v=>updateList('constraints.soft',v)}/><RuleList title="目标公司" help="公司轮搜索计划" value={pack.companies.target} onChange={v=>updateList('companies.target',v)}/><RuleList title="目标职位" help="包含精确职位" value={pack.roles.exact} onChange={v=>updateList('roles.exact',v)}/><RuleList title="正面证据" help="简历中需要看到的经历" value={pack.evidence.required} onChange={v=>updateList('evidence.required',v)}/><RuleList title="明确反证" help="仅明确命中时才排除" value={pack.evidence.negative} onChange={v=>updateList('evidence.negative',v)}/></div><div className="action-bar"><button className="ghost" onClick={saveRules}>保存为新版本</button><button className="primary" onClick={approve} disabled={pack.approval.status==='approved'}>批准规则</button><button className="accent" onClick={()=>setView('run')} disabled={pack.approval.status!=='approved'}>进入筛选 →</button></div></>}</section>}
      {view==='run'&&<section className="run-panel">{!selected?<Empty text="请先选择并批准一个岗位"/>:<><div className="run-hero"><div className="pulse">▶</div><div><p className="eyebrow">DEMO SCREENING RUN</p><h2>双轮模拟筛选</h2><p>公司轮 + 职位轮 · 稳定 ID 去重 · 每批最多 50 人</p></div></div><div className="run-steps"><div><b>1</b><span>合并双轮候选人</span></div><div><b>2</b><span>规则优先判断</span></div><div><b>3</b><span>配置后由 DeepSeek 脱敏分析复核项</span></div><div><b>4</b><span>保存证据与断点</span></div></div>{!currentRun?<button className="primary huge" onClick={startRun} disabled={busy}>创建模拟运行</button>:<><p className="center">进度 {currentRun.cursor} / {currentRun.total} · {currentRun.status==='paused'?'已暂停':currentRun.status==='completed'?'已完成':'运行中'}</p><div className="action-bar"><button className="primary" onClick={processRun} disabled={busy||currentRun.status!=='running'}>处理下一批</button>{currentRun.status==='running'&&<button className="ghost" onClick={async()=>setCurrentRun(await api.pauseRun(currentRun.id))}>暂停</button>}{currentRun.status==='paused'&&<button className="ghost" onClick={async()=>setCurrentRun(await api.resumeRun(currentRun.id))}>恢复</button>}{currentRun.status==='completed'&&<button className="accent" onClick={()=>setView('results')}>查看结果</button>}</div></>}<p className="muted center">当前不会操作真实谷露页面</p></>}</section>}
      {view==='results'&&<section>{!selected?<Empty text="请先完成一次筛选"/>:<><div className="metrics"><Metric label="全部" value={results.length} color="blue"/><Metric label="推荐" value={counts.recommend} color="green"/><Metric label="复核" value={counts.review} color="amber"/><Metric label="排除" value={counts.exclude} color="red"/></div><div className="results-toolbar"><div className="filters">{[['all','全部'],['recommend','推荐'],['review','复核'],['exclude','排除']].map(x=><button className={filter===x[0]?'on':''} onClick={()=>setFilter(x[0])}>{x[1]}</button>)}</div><div><a className="button ghost" href={`/api/jobs/${selected}/export.csv`}>导出 CSV</a><a className="button primary" href={`/api/jobs/${selected}/export.xlsx`}>导出 Excel</a></div></div><div className="result-list">{shown.map(item=><ResultCard key={item.candidateId} item={item} jobId={selected} onSaved={()=>api.results(selected).then(x=>setResults(x.items))}/>)}</div></>}</section>}
      {view==='settings'&&<section className="settings-grid"><div className="panel"><div className="panel-title"><span className="step">AI</span><div><h2>DeepSeek 连接测试</h2><p>实际筛选配置从启动时的 .env 读取；Key 不会显示或保存</p></div></div><label>测试 API 地址<input value={baseUrl} onChange={e=>setBaseUrl(e.target.value)}/></label><label>测试模型<input value={model} onChange={e=>setModel(e.target.value)}/></label><button className="primary" onClick={async()=>{setBusy(true);try{const r=await api.testDeepSeek(baseUrl,model);setNotice(r.ok?`连接成功 · ${r.latencyMs}ms · ${r.model}`:`连接未就绪：${r.errorType}`)}finally{setBusy(false)}}}>测试连接</button></div><div className="panel safety-list"><h2>隐私检查</h2>{['姓名和联系方式不进入 AI','谷露 ID 与详情链接只留本机','日志不保存简历正文','API Key 不写入数据库','年龄、性别、婚育不参与判断'].map(x=><p><span>✓</span>{x}</p>)}</div></section>}
    </main></div>
}

function Empty({text}:{text:string}){return <div className="empty large">◇<br/>{text}</div>}
function Metric({label,value,color}:{label:string;value:number;color:string}){return <div className={`metric ${color}`}><small>{label}</small><strong>{value}</strong></div>}
function RuleList({title,help,value,onChange}:{title:string;help:string;value:string[];onChange:(v:string[])=>void}){return <div className="rule-card"><h3>{title}</h3><p>{help}</p><textarea value={value.join('\n')} onChange={e=>onChange(e.target.value.split('\n').map(x=>x.trim()).filter(Boolean))} placeholder="每行一条规则"/></div>}
function ResultCard({item,jobId,onSaved}:{item:ResultItem;jobId:string;onSaved:()=>void}){const [note,setNote]=useState(item.note);const [status,setStatus]=useState(item.reviewStatus);return <article className="result-card"><div className={`label ${item.label}`}>{labels[item.label]}</div><div className="person"><h3>{item.name}</h3><p>{item.currentCompany} · {item.currentRole}</p><small>{item.sourceRound==='company'?'公司轮':'职位轮'} · 规则 v{item.ruleVersion}</small></div><div className="evidence"><b>{item.reasonCode}</b>{item.evidence.map(x=><p>• {x}</p>)}</div><div className="review"><select value={status} onChange={e=>setStatus(e.target.value)}><option>未审核</option><option>已复核</option><option>需沟通</option></select><input placeholder="人工备注" value={note} onChange={e=>setNote(e.target.value)}/><button onClick={async()=>{await api.review(jobId,item.candidateId,item.ruleVersion,status,note);onSaved()}}>保存</button></div></article>}
